In [2]:
import numpy as np

In [3]:
np.zeros((3, 4, 5), dtype = "int64")

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [4]:
np.linspace(5, 995, num=30, dtype = "int64")

array([  5,  39,  73, 107, 141, 175, 209, 243, 278, 312, 346, 380, 414,
       448, 482, 517, 551, 585, 619, 653, 687, 721, 756, 790, 824, 858,
       892, 926, 960, 995])

In [5]:
test_setup = np.linspace(5, 995, num=4, dtype = "int64")

In [6]:
print(test_setup)

[  5 335 665 995]


In [7]:
test = [i for i in test_setup]

In [8]:
test

[5, 335, 665, 995]

In [11]:
data_matrix = np.zeros((2, 120, 4), dtype = "int64")

In [12]:
data_matrix[0][0]

array([0, 0, 0, 0])

In [15]:
data_matrix[0][0] = data_matrix[0][0] + [5, 335, 665, 995]

In [16]:
data_matrix

array([[[  5, 335, 665, 995],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [ 